@echo off

set F=%~dp0Views\Home\Generated.cshtml

echo @{ ViewData["Title"] = "Generated View"; } >%F%
echo ^<h1^>@ViewData["Title"]^</h1^>^<p^>This view was generated by an external process pre-build.^</p^> >>%F%
